# Form implementation generated from reading ui file '.\templates\dlg_calendar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_calendar(object):
    def setupUi(self, dlg_calendar):
        dlg_calendar.setObjectName("dlg_calendar")
        dlg_calendar.resize(400, 300)
        dlg_calendar.setMinimumSize(QtCore.QSize(400, 300))
        dlg_calendar.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlg_calendar.setWindowIcon(icon)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=dlg_calendar)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 399, 299))
        self.calendarWidget.setMinimumSize(QtCore.QSize(399, 299))
        self.calendarWidget.setMaximumSize(QtCore.QSize(399, 299))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(dlg_calendar)
        QtCore.QMetaObject.connectSlotsByName(dlg_calendar)

    def retranslateUi(self, dlg_calendar):
        _translate = QtCore.QCoreApplication.translate
        dlg_calendar.setWindowTitle(_translate("dlg_calendar", "Calendar"))
