# Form implementation generated from reading ui file '.\templates\dlg_about.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_about(object):
    def setupUi(self, dlg_about):
        dlg_about.setObjectName("dlg_about")
        dlg_about.resize(400, 300)
        dlg_about.setMinimumSize(QtCore.QSize(400, 300))
        dlg_about.setMaximumSize(QtCore.QSize(400, 300))
        self.lbl_icon = QtWidgets.QLabel(parent=dlg_about)
        self.lbl_icon.setGeometry(QtCore.QRect(150, 30, 111, 121))
        self.lbl_icon.setText("")
        self.lbl_icon.setPixmap(QtGui.QPixmap(".\\templates\\../img/icon.png"))
        self.lbl_icon.setObjectName("lbl_icon")
        self.widget = QtWidgets.QWidget(parent=dlg_about)
        self.widget.setGeometry(QtCore.QRect(10, 10, 382, 287))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.view_icon = QtWidgets.QGraphicsView(parent=self.widget)
        self.view_icon.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.view_icon.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.view_icon.setObjectName("view_icon")
        self.verticalLayout.addWidget(self.view_icon)
        self.lbl_MOTD = QtWidgets.QLabel(parent=self.widget)
        self.lbl_MOTD.setMinimumSize(QtCore.QSize(380, 25))
        self.lbl_MOTD.setMaximumSize(QtCore.QSize(380, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbl_MOTD.setFont(font)
        self.lbl_MOTD.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_MOTD.setObjectName("lbl_MOTD")
        self.verticalLayout.addWidget(self.lbl_MOTD)
        self.lbl_version = QtWidgets.QLabel(parent=self.widget)
        self.lbl_version.setMinimumSize(QtCore.QSize(380, 25))
        self.lbl_version.setMaximumSize(QtCore.QSize(380, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_version.setFont(font)
        self.lbl_version.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout.addWidget(self.lbl_version)
        self.btn_closeAbout = QtWidgets.QPushButton(parent=self.widget)
        self.btn_closeAbout.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_closeAbout.setMaximumSize(QtCore.QSize(80, 25))
        self.btn_closeAbout.setObjectName("btn_closeAbout")
        self.verticalLayout.addWidget(self.btn_closeAbout)

        self.retranslateUi(dlg_about)
        QtCore.QMetaObject.connectSlotsByName(dlg_about)

    def retranslateUi(self, dlg_about):
        _translate = QtCore.QCoreApplication.translate
        dlg_about.setWindowTitle(_translate("dlg_about", "About"))
        self.lbl_MOTD.setText(_translate("dlg_about", "Gestor de clientes de Megaturboempresa Teis"))
        self.lbl_version.setText(_translate("dlg_about", "V. 0.0.1"))
        self.btn_closeAbout.setText(_translate("dlg_about", "Close"))
