# Form implementation generated from reading ui file '.\templates\dlg_about.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_about(object):
    def setupUi(self, dlg_about):
        dlg_about.setObjectName("dlg_about")
        dlg_about.resize(400, 300)
        dlg_about.setMinimumSize(QtCore.QSize(400, 300))
        dlg_about.setMaximumSize(QtCore.QSize(400, 300))
        self.view_icon = QtWidgets.QGraphicsView(parent=dlg_about)
        self.view_icon.setGeometry(QtCore.QRect(60, 10, 256, 192))
        self.view_icon.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.view_icon.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.view_icon.setObjectName("view_icon")
        self.lbl_MOTD = QtWidgets.QLabel(parent=dlg_about)
        self.lbl_MOTD.setGeometry(QtCore.QRect(60, 210, 260, 25))
        self.lbl_MOTD.setMinimumSize(QtCore.QSize(256, 25))
        self.lbl_MOTD.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_MOTD.setObjectName("lbl_MOTD")
        self.btn_closeAbout = QtWidgets.QPushButton(parent=dlg_about)
        self.btn_closeAbout.setGeometry(QtCore.QRect(150, 260, 80, 25))
        self.btn_closeAbout.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_closeAbout.setMaximumSize(QtCore.QSize(80, 25))
        self.btn_closeAbout.setObjectName("btn_closeAbout")

        self.retranslateUi(dlg_about)
        QtCore.QMetaObject.connectSlotsByName(dlg_about)

    def retranslateUi(self, dlg_about):
        _translate = QtCore.QCoreApplication.translate
        dlg_about.setWindowTitle(_translate("dlg_about", "About"))
        self.lbl_MOTD.setText(_translate("dlg_about", "TextLabel"))
        self.btn_closeAbout.setText(_translate("dlg_about", "Close"))
