# Form implementation generated from reading ui file '.\templates\window_calendar.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_window_calendar(object):
    def setupUi(self, window_calendar):
        window_calendar.setObjectName("window_calendar")
        window_calendar.resize(400, 300)
        window_calendar.setMinimumSize(QtCore.QSize(400, 300))
        window_calendar.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        window_calendar.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=window_calendar)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 391, 251))
        self.calendar.setMinimumSize(QtCore.QSize(391, 251))
        self.calendar.setMaximumSize(QtCore.QSize(391, 251))
        self.calendar.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.VerticalHeaderFormat.NoVerticalHeader)
        self.calendar.setObjectName("calendar")
        window_calendar.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=window_calendar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        window_calendar.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=window_calendar)
        self.statusbar.setObjectName("statusbar")
        window_calendar.setStatusBar(self.statusbar)

        self.retranslateUi(window_calendar)
        QtCore.QMetaObject.connectSlotsByName(window_calendar)

    def retranslateUi(self, window_calendar):
        _translate = QtCore.QCoreApplication.translate
        window_calendar.setWindowTitle(_translate("window_calendar", "Calendar"))
