# Form implementation generated from reading ui file '.\templates\window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_dnicif = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_dnicif.setGeometry(QtCore.QRect(50, 20, 47, 13))
        self.lbl_dnicif.setObjectName("lbl_dnicif")
        self.txt_dnicif = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_dnicif.setGeometry(QtCore.QRect(100, 20, 113, 20))
        self.txt_dnicif.setObjectName("txt_dnicif")
        self.lbl_nombre = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_nombre.setGeometry(QtCore.QRect(40, 80, 47, 13))
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.lbl_apellidos = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_apellidos.setGeometry(QtCore.QRect(30, 50, 47, 13))
        self.lbl_apellidos.setObjectName("lbl_apellidos")
        self.lbl_fechaalta = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_fechaalta.setGeometry(QtCore.QRect(480, 20, 61, 16))
        self.lbl_fechaalta.setObjectName("lbl_fechaalta")
        self.txt_nombre = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_nombre.setGeometry(QtCore.QRect(100, 80, 250, 20))
        self.txt_nombre.setMinimumSize(QtCore.QSize(250, 0))
        self.txt_nombre.setObjectName("txt_nombre")
        self.txt_apellidos = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_apellidos.setGeometry(QtCore.QRect(100, 50, 250, 20))
        self.txt_apellidos.setMinimumSize(QtCore.QSize(250, 0))
        self.txt_apellidos.setObjectName("txt_apellidos")
        self.txt_fechaalta = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_fechaalta.setGeometry(QtCore.QRect(550, 20, 113, 20))
        self.txt_fechaalta.setObjectName("txt_fechaalta")
        self.btn_calendario = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_calendario.setGeometry(QtCore.QRect(680, 20, 24, 24))
        self.btn_calendario.setMinimumSize(QtCore.QSize(24, 24))
        self.btn_calendario.setMaximumSize(QtCore.QSize(24, 24))
        self.btn_calendario.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\templates\\../img/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_calendario.setIcon(icon)
        self.btn_calendario.setIconSize(QtCore.QSize(32, 32))
        self.btn_calendario.setObjectName("btn_calendario")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuReports = QtWidgets.QMenu(parent=self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuAbout = QtWidgets.QMenu(parent=self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Megaturboempresa Teis"))
        self.lbl_dnicif.setText(_translate("main_window", "DNI/CIF:"))
        self.lbl_nombre.setText(_translate("main_window", "Nombre:"))
        self.lbl_apellidos.setText(_translate("main_window", "Apellidos:"))
        self.lbl_fechaalta.setText(_translate("main_window", "Fecha Alta:"))
        self.menuFile.setTitle(_translate("main_window", "File"))
        self.menuTools.setTitle(_translate("main_window", "Tools"))
        self.menuReports.setTitle(_translate("main_window", "Reports"))
        self.menuAbout.setTitle(_translate("main_window", "About"))
